baseurl = "https://TODO.github.io"
DefaultContentLanguage = "en"
title = "PEPR IA Foundry"
# Using theme as git submodule
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
  homeTitle = "PEPR IA FOUNDRY" # Set a different text for the header on the home page
  subtitle = "Foundations of robustness and reliability in artificial intelligence"
  mainSections = []
  logo = "f2030_ia.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Panayotis Mertikopoulos"
  # website = "yourwebsite.com"
  # email = "youremail@domain.com"
  # github = "username"

# [[menu.main]]
#     name = "Blog"
#     url = ""
#     weight = 1

[[menu.main]]
    name = "Members"
    url = "page/members/"
    weight = 3

[[menu.main]]
    name = "Publications"
    url = "page/publications/"
    weight = 4

# [[menu.main]]
#     identifier = "samples"
#     name = "Samples"
#     weight = 2

[[module.imports]]
  path = "github.com/halogenica/beautifulhugo"
